# Generated by Django 2.2.26 on 2022-05-03 22:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RadiDept',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('Echo', 'Echo'), ('Xray', 'Xray')], default='', max_length=15, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='RadiTestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(choices=[('Echo-General', 'Echo-General'), ('Echo Special', 'Echo-Special'), ('Xray-General', 'Xray-General'), ('Xray-Special', 'Xray-Special')], max_length=50, unique=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RadiDept')),
            ],
        ),
        migrations.CreateModel(
            name='RadiTestType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(default='', max_length=15, unique=True)),
                ('cost', models.IntegerField(default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.RadiTestCategory')),
            ],
        ),
    ]
